[project]
name = "packsureai"
version = "0.1.0"
description = "Backend foundation for PackSure AI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "numpy",
    "opencv-python",
    "pydantic",
    "pytesseract>=0.3.13",
    "python-multipart",
    "requests",
    "uvicorn",
]

[dependency-groups]
dev = [
    "httpx2",
    "pytest",
]
